/**
 * Gamification rules config — faithful mapping of the product spec plus
 * Phase 12 additions (profile, referrals, social graph, content, deep engagement).
 *
 * Used by the seed route to populate GamificationRule.
 * The engine reads rules from DB at runtime; this file is seed-only.
 *
 * Every rule now includes:
 *   label       — short UI display name (e.g. "Daily Login")
 *   description — user-facing "why you earned this" explanation
 */

export const GAMIFICATION_RULES = [
  // =========================================================================
  // FAMILY: user_retention — OBJECTIVE: login_bonus
  // =========================================================================
  {
    id: "login_daily",
    family: "user_retention",
    objective: "login_bonus",
    type: "activity",
    active: true,
    label: "Daily Login",
    description: "You logged in today — every login builds your Overachiever legacy!",
    brandedName: "Overachiever",
    looped: true,
    loopFrequency: "daily",
    points: 100,
    eventType: "user_login",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 18000,
    etaNote: null,
    metadata: null,
  },
  {
    id: "login_streak_2",
    family: "user_retention",
    objective: "login_bonus",
    type: "milestone",
    active: true,
    label: "2-Day Streak",
    description: "Two days in a row — momentum is building!",
    brandedName: "Overachiever",
    looped: false,
    loopFrequency: null,
    points: 120,
    eventType: "user_login",
    thresholdCount: 2,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 14520,
    etaNote: null,
    metadata: { streakDays: 2 },
  },
  {
    id: "login_streak_3",
    family: "user_retention",
    objective: "login_bonus",
    type: "milestone",
    active: true,
    label: "3-Day Streak",
    description: "Three consecutive days — you're on fire!",
    brandedName: "Overachiever",
    looped: false,
    loopFrequency: null,
    points: 160,
    eventType: "user_login",
    thresholdCount: 3,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 14560,
    etaNote: null,
    metadata: { streakDays: 3 },
  },
  {
    id: "login_streak_4",
    family: "user_retention",
    objective: "login_bonus",
    type: "milestone",
    active: true,
    label: "4-Day Streak",
    description: "Four days straight — the dedication is showing!",
    brandedName: "Overachiever",
    looped: false,
    loopFrequency: null,
    points: 200,
    eventType: "user_login",
    thresholdCount: 4,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 14600,
    etaNote: null,
    metadata: { streakDays: 4 },
  },
  {
    id: "login_streak_5",
    family: "user_retention",
    objective: "login_bonus",
    type: "milestone",
    active: true,
    label: "5-Day Streak",
    description: "Halfway to a perfect week — incredible consistency!",
    brandedName: "Overachiever",
    looped: false,
    loopFrequency: null,
    points: 280,
    eventType: "user_login",
    thresholdCount: 5,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 16800,
    etaNote: null,
    metadata: { streakDays: 5 },
  },
  {
    id: "login_streak_6",
    family: "user_retention",
    objective: "login_bonus",
    type: "milestone",
    active: true,
    label: "6-Day Streak",
    description: "Six days running — almost at the weekly jackpot!",
    brandedName: "Overachiever",
    looped: false,
    loopFrequency: null,
    points: 350,
    eventType: "user_login",
    thresholdCount: 6,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 18200,
    etaNote: null,
    metadata: { streakDays: 6 },
  },
  {
    id: "login_streak_7",
    family: "user_retention",
    objective: "login_bonus",
    type: "milestone",
    active: true,
    label: "Weekly Streak",
    description: "Perfect 7-day streak — you're an Overachiever, no doubt about it!",
    brandedName: "Overachiever",
    looped: true,
    loopFrequency: "weekly",
    points: 500,
    eventType: "user_login",
    thresholdCount: 7,
    badgeActive: true,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 26000,
    etaNote: null,
    metadata: { streakDays: 7 },
  },

  // =========================================================================
  // FAMILY: user_retention — OBJECTIVE: gamer_bonus_daily
  // =========================================================================
  {
    id: "gamer_bonus_1h_daily",
    family: "user_retention",
    objective: "gamer_bonus_daily",
    type: "activity",
    active: true,
    label: "1h Gaming Today",
    description: "You played for at least 1 hour today — keeping the Relentless spirit alive!",
    brandedName: "Relentless",
    looped: true,
    loopFrequency: "daily",
    points: 10,
    eventType: "game_hours_daily",
    thresholdCount: null,
    badgeActive: true,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 3650,
    etaNote: null,
    metadata: { requiredHours: 1, comment: "Will run once every 24hrs" },
  },
  {
    id: "gamer_bonus_2h_daily",
    family: "user_retention",
    objective: "gamer_bonus_daily",
    type: "milestone",
    active: false,
    label: "2h Gaming Today",
    description: "You played for at least 2 hours today — serious commitment!",
    brandedName: "Relentless",
    looped: false,
    loopFrequency: null,
    points: null,
    eventType: "game_hours_daily",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 0,
    etaNote: null,
    metadata: { requiredHours: 2 },
  },
  {
    id: "gamer_bonus_3h_daily",
    family: "user_retention",
    objective: "gamer_bonus_daily",
    type: "milestone",
    active: false,
    label: "3h Gaming Today",
    description: "Three hours of gaming today — you're deeply in the zone!",
    brandedName: "Relentless",
    looped: false,
    loopFrequency: null,
    points: null,
    eventType: "game_hours_daily",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 0,
    etaNote: null,
    metadata: { requiredHours: 3 },
  },

  // =========================================================================
  // FAMILY: user_retention — OBJECTIVE: gamer_bonus_weekly
  // =========================================================================
  {
    id: "gamer_bonus_7h_weekly",
    family: "user_retention",
    objective: "gamer_bonus_weekly",
    type: "activity",
    active: true,
    label: "7h Gaming This Week",
    description: "7 hours of gaming this week — true dedication to the craft!",
    brandedName: "Relentless",
    looped: true,
    loopFrequency: "weekly",
    points: 10,
    eventType: "game_hours_weekly",
    thresholdCount: null,
    badgeActive: true,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 520,
    etaNote: null,
    metadata: { requiredHours: 7 },
  },
  {
    id: "gamer_bonus_14h_weekly",
    family: "user_retention",
    objective: "gamer_bonus_weekly",
    type: "milestone",
    active: false,
    label: "14h Gaming This Week",
    description: "14 hours of gaming this week — you live for this!",
    brandedName: "Relentless",
    looped: false,
    loopFrequency: null,
    points: null,
    eventType: "game_hours_weekly",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 0,
    etaNote: null,
    metadata: { requiredHours: 14 },
  },
  {
    id: "gamer_bonus_21h_weekly",
    family: "user_retention",
    objective: "gamer_bonus_weekly",
    type: "milestone",
    active: false,
    label: "21h Gaming This Week",
    description: "21 hours of gaming this week — gaming is your full-time calling!",
    brandedName: "Relentless",
    looped: false,
    loopFrequency: null,
    points: null,
    eventType: "game_hours_weekly",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 0,
    etaNote: null,
    metadata: { requiredHours: 21 },
  },

  // =========================================================================
  // FAMILY: prerequisite — OBJECTIVE: profile_social
  // =========================================================================
  {
    id: "social_any_first",
    family: "prerequisite",
    objective: "profile_social",
    type: "activity",
    active: true,
    label: "First Social Connected",
    description: "You linked your first social account — your Public Figure journey begins!",
    brandedName: "Public Figure",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "social_connected",
    thresholdCount: 1,
    badgeActive: true,
    badgeTier: null,
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 1150,
    etaNote: null,
    metadata: { provider: null },
  },
  {
    id: "social_twitter",
    family: "prerequisite",
    objective: "profile_social",
    type: "activity",
    active: true,
    label: "Twitter Connected",
    description: "Twitter connected — your gaming content reaches the whole community!",
    brandedName: "Public Figure",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "social_connected",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: "tbd",
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 1150,
    etaNote: null,
    metadata: { provider: "twitter" },
  },
  {
    id: "social_instagram",
    family: "prerequisite",
    objective: "profile_social",
    type: "activity",
    active: true,
    label: "Instagram Connected",
    description: "Instagram connected — show the world your gaming aesthetic!",
    brandedName: "Public Figure",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "social_connected",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: "tbd",
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 1150,
    etaNote: null,
    metadata: { provider: "instagram" },
  },
  {
    id: "social_youtube",
    family: "prerequisite",
    objective: "profile_social",
    type: "activity",
    active: true,
    label: "YouTube Connected",
    description: "YouTube connected — your channel is now part of your Leet9 identity!",
    brandedName: "Public Figure",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "social_connected",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: "tbd",
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 1150,
    etaNote: null,
    metadata: { provider: "youtube" },
  },
  {
    id: "social_twitch",
    family: "prerequisite",
    objective: "profile_social",
    type: "activity",
    active: true,
    label: "Twitch Connected",
    description: "Twitch connected — let your viewers find you on Leet9!",
    brandedName: "Public Figure",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "social_connected",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: "tbd",
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 1150,
    etaNote: null,
    metadata: { provider: "twitch" },
  },

  // =========================================================================
  // FAMILY: prerequisite — OBJECTIVE: profile_achievements (Active: No)
  // =========================================================================
  {
    id: "achievement_first_1",
    family: "prerequisite",
    objective: "profile_achievements",
    type: "activity",
    active: false,
    label: "First Achievement",
    description: "You unlocked your very first gaming achievement — the journey begins here!",
    brandedName: null,
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "achievement_unlocked",
    thresholdCount: 1,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 1150,
    etaNote: null,
    metadata: null,
  },
  {
    id: "achievement_first_10",
    family: "prerequisite",
    objective: "profile_achievements",
    type: "activity",
    active: false,
    label: "10 Achievements",
    description: "10 achievements unlocked — a solid start to your achievement hunting career!",
    brandedName: null,
    looped: false,
    loopFrequency: null,
    points: 500,
    eventType: "achievement_unlocked",
    thresholdCount: 10,
    badgeActive: false,
    badgeTier: "bronze",
    badgeCollectionPoints: 2000,
    badgeVisible: true,
    yearlyMaxPoints: 2500,
    etaNote: null,
    metadata: null,
  },
  {
    id: "achievement_first_50",
    family: "prerequisite",
    objective: "profile_achievements",
    type: "activity",
    active: false,
    label: "50 Achievements",
    description: "50 achievements — you're clearly in it for more than just the story!",
    brandedName: null,
    looped: false,
    loopFrequency: null,
    points: 1000,
    eventType: "achievement_unlocked",
    thresholdCount: 50,
    badgeActive: false,
    badgeTier: "silver",
    badgeCollectionPoints: 15000,
    badgeVisible: true,
    yearlyMaxPoints: 16000,
    etaNote: null,
    metadata: null,
  },
  {
    id: "achievement_first_100",
    family: "prerequisite",
    objective: "profile_achievements",
    type: "activity",
    active: false,
    label: "100 Achievements",
    description: "100 achievements unlocked — a certified achievement hunter on the rise!",
    brandedName: null,
    looped: false,
    loopFrequency: null,
    points: 1500,
    eventType: "achievement_unlocked",
    thresholdCount: 100,
    badgeActive: false,
    badgeTier: "gold",
    badgeCollectionPoints: 50000,
    badgeVisible: true,
    yearlyMaxPoints: 51500,
    etaNote: null,
    metadata: null,
  },

  // =========================================================================
  // FAMILY: prerequisite — OBJECTIVE: profile_gaming_accounts
  // =========================================================================
  {
    id: "gaming_account_1",
    family: "prerequisite",
    objective: "profile_gaming_accounts",
    type: "activity",
    active: true,
    label: "First Gaming Account",
    description: "You connected your first gaming platform — your real gaming data is now live!",
    brandedName: "Versatile Gamer",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "gaming_account_connected",
    thresholdCount: 1,
    badgeActive: true,
    badgeTier: null,
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 1150,
    etaNote: null,
    metadata: null,
  },
  {
    id: "gaming_account_5",
    family: "prerequisite",
    objective: "profile_gaming_accounts",
    type: "activity",
    active: true,
    label: "5 Platforms Connected",
    description: "5 gaming platforms connected — you're truly a Versatile Gamer!",
    brandedName: "Versatile Gamer",
    looped: false,
    loopFrequency: null,
    points: 500,
    eventType: "gaming_account_connected",
    thresholdCount: 5,
    badgeActive: false,
    badgeTier: "bronze",
    badgeCollectionPoints: 2000,
    badgeVisible: true,
    yearlyMaxPoints: 2500,
    etaNote: null,
    metadata: null,
  },
  {
    id: "gaming_account_10",
    family: "prerequisite",
    objective: "profile_gaming_accounts",
    type: "activity",
    active: true,
    label: "10 Platforms Connected",
    description: "10 gaming platforms connected — you're conquering every gaming ecosystem!",
    brandedName: "Versatile Gamer",
    looped: false,
    loopFrequency: null,
    points: 1000,
    eventType: "gaming_account_connected",
    thresholdCount: 10,
    badgeActive: false,
    badgeTier: "silver",
    badgeCollectionPoints: 15000,
    badgeVisible: true,
    yearlyMaxPoints: 16000,
    etaNote: null,
    metadata: null,
  },
  {
    id: "gaming_account_15",
    family: "prerequisite",
    objective: "profile_gaming_accounts",
    type: "activity",
    active: true,
    label: "15 Platforms Connected",
    description: "15 gaming accounts linked — absolute mastery of the gaming multiverse!",
    brandedName: "Versatile Gamer",
    looped: false,
    loopFrequency: null,
    points: 1500,
    eventType: "gaming_account_connected",
    thresholdCount: 15,
    badgeActive: false,
    badgeTier: "gold",
    badgeCollectionPoints: 50000,
    badgeVisible: true,
    yearlyMaxPoints: 51500,
    etaNote: null,
    metadata: null,
  },

  // =========================================================================
  // FAMILY: prerequisite — OBJECTIVE: profile_web3
  // =========================================================================
  {
    id: "web3_wallet_1",
    family: "prerequisite",
    objective: "profile_web3",
    type: "activity",
    active: true,
    label: "First Wallet Connected",
    description: "Web3 wallet connected — you've stepped into the blockchain gaming world!",
    brandedName: "Blockchainer",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "web3_wallet_connected",
    thresholdCount: 1,
    badgeActive: true,
    badgeTier: "bronze",
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 3450,
    etaNote: null,
    metadata: { walletCount: 1 },
  },
  {
    id: "web3_wallet_2",
    family: "prerequisite",
    objective: "profile_web3",
    type: "activity",
    active: true,
    label: "2nd Wallet Connected",
    description: "Second wallet linked — a true Blockchainer building their on-chain identity!",
    brandedName: "Blockchainer",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "web3_wallet_connected",
    thresholdCount: 2,
    badgeActive: false,
    badgeTier: "silver",
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 1150,
    etaNote: null,
    metadata: { walletCount: 2 },
  },
  {
    id: "web3_wallet_3",
    family: "prerequisite",
    objective: "profile_web3",
    type: "activity",
    active: true,
    label: "3rd Wallet Connected",
    description: "Three wallets connected — you're all in on the decentralized future!",
    brandedName: "Blockchainer",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "web3_wallet_connected",
    thresholdCount: 3,
    badgeActive: false,
    badgeTier: "gold",
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 1150,
    etaNote: null,
    metadata: { walletCount: 3 },
  },

  // =========================================================================
  // FAMILY: sharing — OBJECTIVE: sharing_badges
  // =========================================================================
  {
    id: "share_achievement_any",
    family: "sharing",
    objective: "sharing_badges",
    type: "activity",
    active: true,
    label: "Achievement Shared",
    description: "You shared a gaming achievement — spreading the hype and growing Leet9's reach!",
    brandedName: "Most Wanted",
    looped: true,
    loopFrequency: null,
    points: 150,
    eventType: "achievement_shared",
    thresholdCount: null,
    badgeActive: true,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: false,
    yearlyMaxPoints: 54750,
    etaNote: null,
    metadata: null,
  },
  {
    id: "share_achievement_25",
    family: "sharing",
    objective: "sharing_badges",
    type: "milestone",
    active: true,
    label: "25 Shares",
    description: "25 achievements shared — you're consistently putting Leet9 on the map!",
    brandedName: "Most Wanted",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "achievement_shared",
    thresholdCount: 25,
    badgeActive: false,
    badgeTier: "bronze",
    badgeCollectionPoints: 2000,
    badgeVisible: false,
    yearlyMaxPoints: 2150,
    etaNote: null,
    metadata: null,
  },
  {
    id: "share_achievement_100",
    family: "sharing",
    objective: "sharing_badges",
    type: "milestone",
    active: true,
    label: "100 Shares",
    description: "100 shared achievements — you're a sharing legend and Most Wanted ambassador!",
    brandedName: "Most Wanted",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "achievement_shared",
    thresholdCount: 100,
    badgeActive: false,
    badgeTier: "silver",
    badgeCollectionPoints: 15000,
    badgeVisible: false,
    yearlyMaxPoints: 15150,
    etaNote: null,
    metadata: null,
  },
  {
    id: "share_achievement_250",
    family: "sharing",
    objective: "sharing_badges",
    type: "milestone",
    active: true,
    label: "250 Shares",
    description: "250 achievements shared across the internet — your reach is unmatched!",
    brandedName: "Most Wanted",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "achievement_shared",
    thresholdCount: 250,
    badgeActive: false,
    badgeTier: "gold",
    badgeCollectionPoints: 50000,
    badgeVisible: false,
    yearlyMaxPoints: 50150,
    etaNote: "1",
    metadata: null,
  },

  // =========================================================================
  // FAMILY: video_game — OBJECTIVE: video_game_activity
  // =========================================================================
  {
    id: "game_added_new",
    family: "video_game",
    objective: "video_game_activity",
    type: "activity",
    active: true,
    label: "New Game Added",
    description: "A new game detected in your library — your collection and Sommelier score grow!",
    brandedName: "Game Sommelier",
    looped: true,
    loopFrequency: null,
    points: 50,
    eventType: "game_added",
    thresholdCount: null,
    badgeActive: true,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 10000,
    etaNote: null,
    metadata: null,
  },
  {
    id: "game_titles_5",
    family: "video_game",
    objective: "video_game_activity",
    type: "milestone",
    active: true,
    label: "5 Games in Library",
    description: "5 different titles in your library — your gaming taste is taking shape!",
    brandedName: "Game Sommelier",
    looped: false,
    loopFrequency: null,
    points: 100,
    eventType: "game_added",
    thresholdCount: 5,
    badgeActive: false,
    badgeTier: "bronze",
    badgeCollectionPoints: 500,
    badgeVisible: true,
    yearlyMaxPoints: 600,
    etaNote: null,
    metadata: null,
  },
  {
    id: "game_titles_25",
    family: "video_game",
    objective: "video_game_activity",
    type: "milestone",
    active: true,
    label: "25 Games in Library",
    description: "25 games in your collection — a serious gamer's library is taking form!",
    brandedName: "Game Sommelier",
    looped: false,
    loopFrequency: null,
    points: 100,
    eventType: "game_added",
    thresholdCount: 25,
    badgeActive: false,
    badgeTier: "silver",
    badgeCollectionPoints: 5000,
    badgeVisible: true,
    yearlyMaxPoints: 5100,
    etaNote: null,
    metadata: null,
  },
  {
    id: "game_titles_250",
    family: "video_game",
    objective: "video_game_activity",
    type: "milestone",
    active: true,
    label: "250 Games in Library",
    description: "250 titles in your library — you're a true Game Sommelier connoisseur!",
    brandedName: "Game Sommelier",
    looped: false,
    loopFrequency: null,
    points: 100,
    eventType: "game_added",
    thresholdCount: 250,
    badgeActive: false,
    badgeTier: "gold",
    badgeCollectionPoints: 20000,
    badgeVisible: true,
    yearlyMaxPoints: 20100,
    etaNote: "1 year",
    metadata: null,
  },

  // =========================================================================
  // PHASE 12 — PROFILE COMPLETENESS
  // FAMILY: profile_completeness — OBJECTIVE: profile_complete
  // brandedName: "Persona"
  // =========================================================================
  {
    id: "profile_avatar",
    family: "profile_completeness",
    objective: "profile_complete",
    type: "activity",
    active: true,
    label: "Avatar Set",
    description: "You set a profile picture — your gaming identity just levelled up!",
    brandedName: "Persona",
    looped: false,
    loopFrequency: null,
    points: 200,
    eventType: "profile_updated",
    thresholdCount: null,
    badgeActive: true,
    badgeTier: "bronze",
    badgeCollectionPoints: 200,
    badgeVisible: true,
    yearlyMaxPoints: 200,
    etaNote: null,
    metadata: { field: "avatar" },
  },
  {
    id: "profile_bio",
    family: "profile_completeness",
    objective: "profile_complete",
    type: "activity",
    active: true,
    label: "Bio Written",
    description: "You introduced yourself with a bio — other gamers can now see who you are!",
    brandedName: "Persona",
    looped: false,
    loopFrequency: null,
    points: 200,
    eventType: "profile_updated",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: "silver",
    badgeCollectionPoints: 400,
    badgeVisible: true,
    yearlyMaxPoints: 200,
    etaNote: null,
    metadata: { field: "bio" },
  },
  {
    id: "profile_location",
    family: "profile_completeness",
    objective: "profile_complete",
    type: "activity",
    active: true,
    label: "Location Added",
    description: "You added your location — representing your region in the global arena!",
    brandedName: "Persona",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "profile_updated",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: "gold",
    badgeCollectionPoints: 550,
    badgeVisible: true,
    yearlyMaxPoints: 150,
    etaNote: null,
    metadata: { field: "location" },
  },

  // =========================================================================
  // PHASE 12 — REFERRALS
  // FAMILY: acquisition — OBJECTIVE: referral
  // brandedName: "Ambassador"
  // =========================================================================
  {
    id: "referral_invited",
    family: "acquisition",
    objective: "referral",
    type: "activity",
    active: true,
    label: "Friend Invited",
    description: "You sent an invite — spreading the word grows the Leet9 community!",
    brandedName: "Ambassador",
    looped: true,
    loopFrequency: null,
    points: 200,
    eventType: "friend_invited",
    thresholdCount: null,
    badgeActive: true,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 4000,
    etaNote: null,
    metadata: null,
  },
  {
    id: "referral_activated_1",
    family: "acquisition",
    objective: "referral",
    type: "activity",
    active: true,
    label: "Friend Joined",
    description: "Someone you invited created their Leet9 account — your network is growing!",
    brandedName: "Ambassador",
    looped: true,
    loopFrequency: null,
    points: 500,
    eventType: "friend_activated",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: "bronze",
    badgeCollectionPoints: 500,
    badgeVisible: true,
    yearlyMaxPoints: 10000,
    etaNote: null,
    metadata: null,
  },
  {
    id: "referral_activated_5",
    family: "acquisition",
    objective: "referral",
    type: "milestone",
    active: true,
    label: "5 Friends Joined",
    description: "5 of your friends joined Leet9 — you're a true ambassador of the community!",
    brandedName: "Ambassador",
    looped: false,
    loopFrequency: null,
    points: 1500,
    eventType: "friend_activated",
    thresholdCount: 5,
    badgeActive: false,
    badgeTier: "silver",
    badgeCollectionPoints: 4000,
    badgeVisible: true,
    yearlyMaxPoints: 11500,
    etaNote: null,
    metadata: null,
  },
  {
    id: "referral_activated_20",
    family: "acquisition",
    objective: "referral",
    type: "milestone",
    active: true,
    label: "20 Friends Joined",
    description: "20 friends joined because of you — you ARE Leet9's biggest ambassador!",
    brandedName: "Ambassador",
    looped: false,
    loopFrequency: null,
    points: 5000,
    eventType: "friend_activated",
    thresholdCount: 20,
    badgeActive: false,
    badgeTier: "gold",
    badgeCollectionPoints: 15000,
    badgeVisible: true,
    yearlyMaxPoints: 16500,
    etaNote: null,
    metadata: null,
  },

  // =========================================================================
  // PHASE 12 — SOCIAL GRAPH
  // FAMILY: social — OBJECTIVE: social_graph
  // brandedName: "Social Star"
  // =========================================================================
  {
    id: "follow_first",
    family: "social",
    objective: "social_graph",
    type: "activity",
    active: true,
    label: "First Follow",
    description: "You followed your first gamer — building your crew one player at a time!",
    brandedName: "Social Star",
    looped: false,
    loopFrequency: null,
    points: 100,
    eventType: "user_followed",
    thresholdCount: 1,
    badgeActive: true,
    badgeTier: "bronze",
    badgeCollectionPoints: 100,
    badgeVisible: true,
    yearlyMaxPoints: 100,
    etaNote: null,
    metadata: null,
  },
  {
    id: "follow_10",
    family: "social",
    objective: "social_graph",
    type: "milestone",
    active: true,
    label: "Following 10",
    description: "You're following 10 gamers — your feed is getting serious!",
    brandedName: "Social Star",
    looped: false,
    loopFrequency: null,
    points: 300,
    eventType: "user_followed",
    thresholdCount: 10,
    badgeActive: false,
    badgeTier: "silver",
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 300,
    etaNote: null,
    metadata: null,
  },
  {
    id: "follower_first",
    family: "social",
    objective: "social_graph",
    type: "activity",
    active: true,
    label: "First Follower",
    description: "Someone followed you — your gaming reputation is on the map!",
    brandedName: "Social Star",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "follower_gained",
    thresholdCount: 1,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 150,
    etaNote: null,
    metadata: null,
  },
  {
    id: "follower_10",
    family: "social",
    objective: "social_graph",
    type: "milestone",
    active: true,
    label: "10 Followers",
    description: "10 gamers are following you — you're becoming a community figure!",
    brandedName: "Social Star",
    looped: false,
    loopFrequency: null,
    points: 500,
    eventType: "follower_gained",
    thresholdCount: 10,
    badgeActive: false,
    badgeTier: "gold",
    badgeCollectionPoints: 5000,
    badgeVisible: true,
    yearlyMaxPoints: 500,
    etaNote: null,
    metadata: null,
  },

  // =========================================================================
  // PHASE 12 — CONTENT CREATION
  // FAMILY: content — OBJECTIVE: content_creation
  // brandedName: "Curator"
  // =========================================================================
  {
    id: "review_first",
    family: "content",
    objective: "content_creation",
    type: "activity",
    active: true,
    label: "First Review",
    description: "You wrote your first game review — your take matters to the community!",
    brandedName: "Curator",
    looped: false,
    loopFrequency: null,
    points: 500,
    eventType: "game_reviewed",
    thresholdCount: 1,
    badgeActive: true,
    badgeTier: "bronze",
    badgeCollectionPoints: 500,
    badgeVisible: true,
    yearlyMaxPoints: 500,
    etaNote: null,
    metadata: null,
  },
  {
    id: "review_5",
    family: "content",
    objective: "content_creation",
    type: "milestone",
    active: true,
    label: "5 Reviews Written",
    description: "You've reviewed 5 games — you're shaping what this community plays!",
    brandedName: "Curator",
    looped: false,
    loopFrequency: null,
    points: 1000,
    eventType: "game_reviewed",
    thresholdCount: 5,
    badgeActive: false,
    badgeTier: "silver",
    badgeCollectionPoints: 2500,
    badgeVisible: true,
    yearlyMaxPoints: 1000,
    etaNote: null,
    metadata: null,
  },
  {
    id: "list_first",
    family: "content",
    objective: "content_creation",
    type: "activity",
    active: true,
    label: "First List Created",
    description: "You curated your first game list — taste-makers run this platform!",
    brandedName: "Curator",
    looped: false,
    loopFrequency: null,
    points: 300,
    eventType: "list_created",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: "gold",
    badgeCollectionPoints: 5000,
    badgeVisible: true,
    yearlyMaxPoints: 300,
    etaNote: null,
    metadata: null,
  },

  // =========================================================================
  // PHASE 12 — DEEP ENGAGEMENT / GAME MASTERY
  // FAMILY: video_game — OBJECTIVE: game_mastery
  // brandedName: "Hardcore"
  // =========================================================================
  {
    id: "game_mastery_500h",
    family: "video_game",
    objective: "game_mastery",
    type: "milestone",
    active: true,
    label: "500h Master",
    description: "500 hours in a single game — you're not just a player, you're a legend of this title!",
    brandedName: "Hardcore",
    looped: false,
    loopFrequency: null,
    points: 2000,
    eventType: "game_hours_single",
    thresholdCount: null,
    badgeActive: true,
    badgeTier: "gold",
    badgeCollectionPoints: 2000,
    badgeVisible: true,
    yearlyMaxPoints: 2000,
    etaNote: null,
    metadata: { requiredHours: 500 },
  },
  {
    id: "game_completionist",
    family: "video_game",
    objective: "game_mastery",
    type: "activity",
    active: true,
    label: "100% Completion",
    description: "100% achievements in a game — obsession is a skill, and you've mastered it!",
    brandedName: "Hardcore",
    looped: true,
    loopFrequency: null,
    points: 1000,
    eventType: "game_completed",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: "bronze",
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 20000,
    etaNote: null,
    metadata: null,
  },

  // =========================================================================
  // PHASE 12 — VETERAN MILESTONES
  // FAMILY: retention — OBJECTIVE: veteran_milestone
  // brandedName: "OG"
  // =========================================================================
  {
    id: "veteran_30",
    family: "retention",
    objective: "veteran_milestone",
    type: "milestone",
    active: true,
    label: "30 Days In",
    description: "You've been on Leet9 for 30 days — you're no longer a newcomer, you're part of the crew!",
    brandedName: "OG",
    looped: false,
    loopFrequency: null,
    points: 500,
    eventType: "veteran_milestone",
    thresholdCount: 30,
    badgeActive: true,
    badgeTier: "bronze",
    badgeCollectionPoints: 500,
    badgeVisible: true,
    yearlyMaxPoints: 500,
    etaNote: null,
    metadata: null,
  },
  {
    id: "veteran_90",
    family: "retention",
    objective: "veteran_milestone",
    type: "milestone",
    active: true,
    label: "90 Days In",
    description: "3 months on Leet9 — the platform is clearly part of your gaming life now!",
    brandedName: "OG",
    looped: false,
    loopFrequency: null,
    points: 1500,
    eventType: "veteran_milestone",
    thresholdCount: 90,
    badgeActive: false,
    badgeTier: "silver",
    badgeCollectionPoints: 2000,
    badgeVisible: true,
    yearlyMaxPoints: 1500,
    etaNote: null,
    metadata: null,
  },
  {
    id: "veteran_180",
    family: "retention",
    objective: "veteran_milestone",
    type: "milestone",
    active: true,
    label: "6 Months OG",
    description: "6 months with Leet9 — you were here before it got big, true OG status!",
    brandedName: "OG",
    looped: false,
    loopFrequency: null,
    points: 5000,
    eventType: "veteran_milestone",
    thresholdCount: 180,
    badgeActive: false,
    badgeTier: "gold",
    badgeCollectionPoints: 7000,
    badgeVisible: true,
    yearlyMaxPoints: 5000,
    etaNote: null,
    metadata: null,
  },
];
