/**
 * Gamification rules config — faithful mapping of the product spec.
 * Used by the seed script to populate GamificationRule.
 * The engine reads rules from the DB at runtime; this file is seed-only.
 *
 * Columns mirror the spec:
 *   family | objective | type | active | description | brandedName |
 *   looped | loopFrequency | points | eventType | thresholdCount |
 *   badgeActive | badgeTier | badgeCollectionPoints | badgeVisible |
 *   yearlyMaxPoints | etaNote | metadata
 */

export const GAMIFICATION_RULES = [
  // =========================================================================
  // FAMILY: user_retention — OBJECTIVE: login_bonus
  // =========================================================================
  {
    id: "login_daily",
    family: "user_retention",
    objective: "login_bonus",
    type: "activity",
    active: true,
    description: "Log in daily to receive points",
    brandedName: "Overachiever",
    looped: true,
    loopFrequency: "daily",
    points: 100,
    eventType: "user_login",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 18000,
    etaNote: null,
    metadata: null,
  },
  {
    id: "login_streak_2",
    family: "user_retention",
    objective: "login_bonus",
    type: "milestone",
    active: true,
    description: "Log in for 2 consecutive days",
    brandedName: "Overachiever",
    looped: false,
    loopFrequency: null,
    points: 120,
    eventType: "user_login",
    thresholdCount: 2,
    badgeActive: false,
    badgeTier: null,       // NA: no badge planned for this row
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 14520,
    etaNote: null,
    metadata: { streakDays: 2 },
  },
  {
    id: "login_streak_3",
    family: "user_retention",
    objective: "login_bonus",
    type: "milestone",
    active: true,
    description: "Log in for 3 consecutive days",
    brandedName: "Overachiever",
    looped: false,
    loopFrequency: null,
    points: 160,
    eventType: "user_login",
    thresholdCount: 3,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 14560,
    etaNote: null,
    metadata: { streakDays: 3 },
  },
  {
    id: "login_streak_4",
    family: "user_retention",
    objective: "login_bonus",
    type: "milestone",
    active: true,
    description: "Log in for 4 consecutive days",
    brandedName: "Overachiever",
    looped: false,
    loopFrequency: null,
    points: 200,
    eventType: "user_login",
    thresholdCount: 4,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 14600,
    etaNote: null,
    metadata: { streakDays: 4 },
  },
  {
    id: "login_streak_5",
    family: "user_retention",
    objective: "login_bonus",
    type: "milestone",
    active: true,
    description: "Log in for 5 consecutive days",
    brandedName: "Overachiever",
    looped: false,
    loopFrequency: null,
    points: 280,
    eventType: "user_login",
    thresholdCount: 5,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 16800,
    etaNote: null,
    metadata: { streakDays: 5 },
  },
  {
    id: "login_streak_6",
    family: "user_retention",
    objective: "login_bonus",
    type: "milestone",
    active: true,
    description: "Log in for 6 consecutive days",
    brandedName: "Overachiever",
    looped: false,
    loopFrequency: null,
    points: 350,
    eventType: "user_login",
    thresholdCount: 6,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 18200,
    etaNote: null,
    metadata: { streakDays: 6 },
  },
  {
    // Looped = resets and re-fires every completed 7-day streak cycle.
    id: "login_streak_7",
    family: "user_retention",
    objective: "login_bonus",
    type: "milestone",
    active: true,
    description: "Log in for 7 consecutive days",
    brandedName: "Overachiever",
    looped: true,
    loopFrequency: "weekly",
    points: 500,
    eventType: "user_login",
    thresholdCount: 7,
    badgeActive: true,
    badgeTier: null,       // NA: badge awarded but no tier hierarchy for this rule
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 26000,
    etaNote: null,
    metadata: { streakDays: 7 },
  },

  // =========================================================================
  // FAMILY: user_retention — OBJECTIVE: gamer_bonus_daily
  // =========================================================================
  {
    // 1Y Max corrected: 10pts × 365 days = 3650 (spec had 87600 — data entry error)
    id: "gamer_bonus_1h_daily",
    family: "user_retention",
    objective: "gamer_bonus_daily",
    type: "activity",
    active: true,
    description: "Played 1 hour at any game daily",
    brandedName: "Relentless",
    looped: true,
    loopFrequency: "daily",
    points: 10,
    eventType: "game_hours_daily",
    thresholdCount: null,
    badgeActive: true,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 3650,
    etaNote: null,
    metadata: { requiredHours: 1, comment: "Will run once every 24hrs" },
  },
  {
    id: "gamer_bonus_2h_daily",
    family: "user_retention",
    objective: "gamer_bonus_daily",
    type: "milestone",
    active: false,         // placeholder — points and badge TBD
    description: "Played 2 hours at any game daily",
    brandedName: "Relentless",
    looped: false,
    loopFrequency: null,
    points: null,          // NA
    eventType: "game_hours_daily",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 0,
    etaNote: null,
    metadata: { requiredHours: 2 },
  },
  {
    id: "gamer_bonus_3h_daily",
    family: "user_retention",
    objective: "gamer_bonus_daily",
    type: "milestone",
    active: false,
    description: "Played 3 hours at any game daily",
    brandedName: "Relentless",
    looped: false,
    loopFrequency: null,
    points: null,
    eventType: "game_hours_daily",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 0,
    etaNote: null,
    metadata: { requiredHours: 3 },
  },

  // =========================================================================
  // FAMILY: user_retention — OBJECTIVE: gamer_bonus_weekly
  // =========================================================================
  {
    // 1Y Max: 10pts × 52 weeks = 520
    id: "gamer_bonus_7h_weekly",
    family: "user_retention",
    objective: "gamer_bonus_weekly",
    type: "activity",
    active: true,
    description: "Played 7 hours at any game weekly",
    brandedName: "Relentless",
    looped: true,
    loopFrequency: "weekly",
    points: 10,
    eventType: "game_hours_weekly",
    thresholdCount: null,
    badgeActive: true,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 520,
    etaNote: null,
    metadata: { requiredHours: 7 },
  },
  {
    id: "gamer_bonus_14h_weekly",
    family: "user_retention",
    objective: "gamer_bonus_weekly",
    type: "milestone",
    active: false,
    description: "Played 14 hours at any game weekly",
    brandedName: "Relentless",
    looped: false,
    loopFrequency: null,
    points: null,
    eventType: "game_hours_weekly",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 0,
    etaNote: null,
    metadata: { requiredHours: 14 },
  },
  {
    id: "gamer_bonus_21h_weekly",
    family: "user_retention",
    objective: "gamer_bonus_weekly",
    type: "milestone",
    active: false,
    description: "Played 21 hours at any game weekly",
    brandedName: "Relentless",
    looped: false,
    loopFrequency: null,
    points: null,
    eventType: "game_hours_weekly",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 0,
    etaNote: null,
    metadata: { requiredHours: 21 },
  },

  // =========================================================================
  // FAMILY: prerequisite — OBJECTIVE: profile_social
  // "Connect One Social Media" fires once on first social connection (any).
  // Per-platform rules fire independently when that specific platform connects.
  // A user connecting Twitter gets both: 150 (first social) + 150 (Twitter) = 300.
  // =========================================================================
  {
    id: "social_any_first",
    family: "prerequisite",
    objective: "profile_social",
    type: "activity",
    active: true,
    description: "Connect One Social Media",
    brandedName: "Public Figure",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "social_connected",
    thresholdCount: 1,     // fires when totalSocials reaches 1 for the first time
    badgeActive: true,
    badgeTier: null,
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 1150,
    etaNote: null,
    metadata: { provider: null }, // null = any provider
  },
  {
    id: "social_twitter",
    family: "prerequisite",
    objective: "profile_social",
    type: "activity",
    active: true,
    description: "Connect Twitter",
    brandedName: "Public Figure",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "social_connected",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: "tbd",
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 1150,
    etaNote: null,
    metadata: { provider: "twitter" },
  },
  {
    id: "social_instagram",
    family: "prerequisite",
    objective: "profile_social",
    type: "activity",
    active: true,
    description: "Connect Instagram",
    brandedName: "Public Figure",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "social_connected",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: "tbd",
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 1150,
    etaNote: null,
    metadata: { provider: "instagram" },
  },
  {
    id: "social_youtube",
    family: "prerequisite",
    objective: "profile_social",
    type: "activity",
    active: true,
    description: "Connect YouTube",
    brandedName: "Public Figure",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "social_connected",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: "tbd",
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 1150,
    etaNote: null,
    metadata: { provider: "youtube" },
  },
  {
    id: "social_twitch",
    family: "prerequisite",
    objective: "profile_social",
    type: "activity",
    active: true,
    description: "Connect Twitch",
    brandedName: "Public Figure",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "social_connected",
    thresholdCount: null,
    badgeActive: false,
    badgeTier: "tbd",
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 1150,
    etaNote: null,
    metadata: { provider: "twitch" },
  },

  // =========================================================================
  // FAMILY: prerequisite — OBJECTIVE: profile_achievements (Active: No)
  // Entire group disabled until product team flips active: true.
  // =========================================================================
  {
    id: "achievement_first_1",
    family: "prerequisite",
    objective: "profile_achievements",
    type: "activity",
    active: false,
    description: "Received the first game Achievement",
    brandedName: null,
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "achievement_unlocked",
    thresholdCount: 1,
    badgeActive: false,
    badgeTier: null,
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 1150,
    etaNote: null,
    metadata: null,
  },
  {
    id: "achievement_first_10",
    family: "prerequisite",
    objective: "profile_achievements",
    type: "activity",
    active: false,
    description: "Received the first 10 game Achievements",
    brandedName: null,
    looped: false,
    loopFrequency: null,
    points: 500,
    eventType: "achievement_unlocked",
    thresholdCount: 10,
    badgeActive: false,
    badgeTier: "bronze",
    badgeCollectionPoints: 2000,
    badgeVisible: true,
    yearlyMaxPoints: 2500,
    etaNote: null,
    metadata: null,
  },
  {
    id: "achievement_first_50",
    family: "prerequisite",
    objective: "profile_achievements",
    type: "activity",
    active: false,
    description: "Received the first 50 game Achievements",
    brandedName: null,
    looped: false,
    loopFrequency: null,
    points: 1000,
    eventType: "achievement_unlocked",
    thresholdCount: 50,
    badgeActive: false,
    badgeTier: "silver",
    badgeCollectionPoints: 15000,
    badgeVisible: true,
    yearlyMaxPoints: 16000,
    etaNote: null,
    metadata: null,
  },
  {
    id: "achievement_first_100",
    family: "prerequisite",
    objective: "profile_achievements",
    type: "activity",
    active: false,
    description: "Received the first 100 game Achievements",
    brandedName: null,
    looped: false,
    loopFrequency: null,
    points: 1500,
    eventType: "achievement_unlocked",
    thresholdCount: 100,
    badgeActive: false,
    badgeTier: "gold",
    badgeCollectionPoints: 50000,
    badgeVisible: true,
    yearlyMaxPoints: 51500,
    etaNote: null,
    metadata: null,
  },

  // =========================================================================
  // FAMILY: prerequisite — OBJECTIVE: profile_gaming_accounts
  // =========================================================================
  {
    id: "gaming_account_1",
    family: "prerequisite",
    objective: "profile_gaming_accounts",
    type: "activity",
    active: true,
    description: "Connect one gaming account",
    brandedName: "Versatile Gamer",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "gaming_account_connected",
    thresholdCount: 1,
    badgeActive: true,
    badgeTier: null,
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 1150,
    etaNote: null,
    metadata: null,
  },
  {
    id: "gaming_account_5",
    family: "prerequisite",
    objective: "profile_gaming_accounts",
    type: "activity",
    active: true,
    description: "Connect 5 Gaming Accounts",
    brandedName: "Versatile Gamer",
    looped: false,
    loopFrequency: null,
    points: 500,
    eventType: "gaming_account_connected",
    thresholdCount: 5,
    badgeActive: false,
    badgeTier: "bronze",
    badgeCollectionPoints: 2000,
    badgeVisible: true,
    yearlyMaxPoints: 2500,
    etaNote: null,
    metadata: null,
  },
  {
    id: "gaming_account_10",
    family: "prerequisite",
    objective: "profile_gaming_accounts",
    type: "activity",
    active: true,
    description: "Connect 10 Gaming Accounts",
    brandedName: "Versatile Gamer",
    looped: false,
    loopFrequency: null,
    points: 1000,
    eventType: "gaming_account_connected",
    thresholdCount: 10,
    badgeActive: false,
    badgeTier: "silver",
    badgeCollectionPoints: 15000,
    badgeVisible: true,
    yearlyMaxPoints: 16000,
    etaNote: null,
    metadata: null,
  },
  {
    id: "gaming_account_15",
    family: "prerequisite",
    objective: "profile_gaming_accounts",
    type: "activity",
    active: true,
    description: "Connect 15 Gaming Accounts",
    brandedName: "Versatile Gamer",
    looped: false,
    loopFrequency: null,
    points: 1500,
    eventType: "gaming_account_connected",
    thresholdCount: 15,
    badgeActive: false,
    badgeTier: "gold",
    badgeCollectionPoints: 50000,
    badgeVisible: true,
    yearlyMaxPoints: 51500,
    etaNote: null,
    metadata: null,
  },

  // =========================================================================
  // FAMILY: prerequisite — OBJECTIVE: profile_web3
  // Silver = 2nd wallet, Gold = 3rd wallet (same action, different count).
  // =========================================================================
  {
    id: "web3_wallet_1",
    family: "prerequisite",
    objective: "profile_web3",
    type: "activity",
    active: true,
    description: "Connect A Web3 Wallet",
    brandedName: "Blockchainer",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "web3_wallet_connected",
    thresholdCount: 1,
    badgeActive: true,
    badgeTier: "bronze",
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 3450,
    etaNote: null,
    metadata: { walletCount: 1 },
  },
  {
    id: "web3_wallet_2",
    family: "prerequisite",
    objective: "profile_web3",
    type: "activity",
    active: true,
    description: "Connect another Web3 Wallet (2nd)",
    brandedName: "Blockchainer",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "web3_wallet_connected",
    thresholdCount: 2,
    badgeActive: false,
    badgeTier: "silver",
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 1150,
    etaNote: null,
    metadata: { walletCount: 2 },
  },
  {
    id: "web3_wallet_3",
    family: "prerequisite",
    objective: "profile_web3",
    type: "activity",
    active: true,
    description: "Connect another Web3 Wallet (3rd)",
    brandedName: "Blockchainer",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "web3_wallet_connected",
    thresholdCount: 3,
    badgeActive: false,
    badgeTier: "gold",
    badgeCollectionPoints: 1000,
    badgeVisible: true,
    yearlyMaxPoints: 1150,
    etaNote: null,
    metadata: { walletCount: 3 },
  },

  // =========================================================================
  // FAMILY: sharing — OBJECTIVE: sharing_badges
  // "Yes Only Points": points engine live, badge display not yet active.
  // badgeVisible: false until UI is ready.
  // =========================================================================
  {
    id: "share_achievement_any",
    family: "sharing",
    objective: "sharing_badges",
    type: "activity",
    active: true,
    description: "Share One Achievement",
    brandedName: "Most Wanted",
    looped: true,
    loopFrequency: null,   // fires on every share, no time-window cap
    points: 150,
    eventType: "achievement_shared",
    thresholdCount: null,
    badgeActive: true,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: false,   // points active, badge UI not ready yet
    yearlyMaxPoints: 54750,
    etaNote: null,
    metadata: null,
  },
  {
    id: "share_achievement_25",
    family: "sharing",
    objective: "sharing_badges",
    type: "milestone",
    active: true,
    description: "Share 25 Achievements",
    brandedName: "Most Wanted",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "achievement_shared",
    thresholdCount: 25,
    badgeActive: false,
    badgeTier: "bronze",
    badgeCollectionPoints: 2000,
    badgeVisible: false,
    yearlyMaxPoints: 2150,
    etaNote: null,
    metadata: null,
  },
  {
    id: "share_achievement_100",
    family: "sharing",
    objective: "sharing_badges",
    type: "milestone",
    active: true,
    description: "Share 100 Achievements",
    brandedName: "Most Wanted",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "achievement_shared",
    thresholdCount: 100,
    badgeActive: false,
    badgeTier: "silver",
    badgeCollectionPoints: 15000,
    badgeVisible: false,
    yearlyMaxPoints: 15150,
    etaNote: null,
    metadata: null,
  },
  {
    id: "share_achievement_250",
    family: "sharing",
    objective: "sharing_badges",
    type: "milestone",
    active: true,
    description: "Share 250 Achievements",
    brandedName: "Most Wanted",
    looped: false,
    loopFrequency: null,
    points: 150,
    eventType: "achievement_shared",
    thresholdCount: 250,
    badgeActive: false,
    badgeTier: "gold",
    badgeCollectionPoints: 50000,
    badgeVisible: false,
    yearlyMaxPoints: 50150,
    etaNote: "1",          // informational phase marker from spec
    metadata: null,
  },

  // =========================================================================
  // FAMILY: video_game — OBJECTIVE: video_game_activity
  // "Play a new game" fires on each new game detected via sync (firstDetectedAt).
  // =========================================================================
  {
    id: "game_added_new",
    family: "video_game",
    objective: "video_game_activity",
    type: "activity",
    active: true,
    description: "Play a new game",
    brandedName: "Game Sommelier",
    looped: true,
    loopFrequency: null,   // fires once per new game detected, no time-window
    points: 50,
    eventType: "game_added",
    thresholdCount: null,
    badgeActive: true,
    badgeTier: null,
    badgeCollectionPoints: null,
    badgeVisible: true,
    yearlyMaxPoints: 10000,
    etaNote: null,
    metadata: null,
  },
  {
    id: "game_titles_5",
    family: "video_game",
    objective: "video_game_activity",
    type: "milestone",
    active: true,
    description: "Play 5 different titles",
    brandedName: "Game Sommelier",
    looped: false,
    loopFrequency: null,
    points: 100,
    eventType: "game_added",
    thresholdCount: 5,
    badgeActive: false,
    badgeTier: "bronze",
    badgeCollectionPoints: 500,
    badgeVisible: true,
    yearlyMaxPoints: 600,
    etaNote: null,
    metadata: null,
  },
  {
    id: "game_titles_25",
    family: "video_game",
    objective: "video_game_activity",
    type: "milestone",
    active: true,
    description: "Play 25 different titles",
    brandedName: "Game Sommelier",
    looped: false,
    loopFrequency: null,
    points: 100,
    eventType: "game_added",
    thresholdCount: 25,
    badgeActive: false,
    badgeTier: "silver",
    badgeCollectionPoints: 5000,
    badgeVisible: true,
    yearlyMaxPoints: 5100,
    etaNote: null,
    metadata: null,
  },
  {
    id: "game_titles_250",
    family: "video_game",
    objective: "video_game_activity",
    type: "milestone",
    active: true,
    description: "Play 250 different titles",
    brandedName: "Game Sommelier",
    looped: false,
    loopFrequency: null,
    points: 100,
    eventType: "game_added",
    thresholdCount: 250,
    badgeActive: false,
    badgeTier: "gold",
    badgeCollectionPoints: 20000,
    badgeVisible: true,
    yearlyMaxPoints: 20100,
    etaNote: "1 year",     // stretch goal marker from spec
    metadata: null,
  },
];
